### ISSUE TITLE
New choices can appear as "voted"

### ISSUE THREAD

**Issue by eaneuhaus** [vanderbilt-redcap/votecap_module#1]
​Our team attempted to use a VoteCap session today and I noticed it behaving strangely. When I opened the link, I saw two choices with green "voted" icons, as if I had already clicked them. Upon actually clicking them, they would go from 0 votes to -1. I had a colleague try to vote as well and she saw the same issue: choices already marked green and clicking them brought the count down to -2.

I did a bit of testing to see if I could nail down the cause. I found that creating a new VoteCap project ​presented the same issue (already "voted" choices), but the third choice I added did NOT appear as green and worked as expected. After playing around with it a bit I think what's happening is that however the "voted/not voted" status for each choice is being saved is being read universally for each new VoteCap project (so, if I voted on the first two options in one session, another totally unrelated session will also display the first two options as "voted").

This does not seem to retroactively affect old sessions (even when adding new options as far as I can tell).

**Comment by taylorr4** [comment]
@eaneuhaus, thanks for letting me know about this bug. It's now been fixed in commit https://github.com/vanderbilt-redcap/votecap_module/commit/1151caa2ad8b64ae6e4f2e22ea359195061621eb. I'll push this out soon as a new version in the REDCap Repo.
